version: '3.7'

services:
  app:
    image: openjdk:16-alpine3.13
    command: sh -c "./mvnw spring-boot:run"
    ports:
      - 80:80
    working-dir: ./app
    volumes:
      - ./:./app
  elasticsearch_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch_540
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300